name: "Pull Request"

on: [push]

permissions:
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.DEPLOY_ROLE }}
          role-session-name: OIDCSession

      - run: aws s3 cp s3://test-fxs/README.md s3://test-fxs/jar/README.md
        shell: bash
        
        
  # write-dev:
  #   runs-on: ubuntu-latest
  #   needs: read-dev
  #   environment: Development
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-region: eu-west-1
  #         role-to-assume: ${{ secrets.DEPLOY_ROLE }}
  #         role-session-name: OIDCSession

  #     - run: aws s3 cp README.md s3://test-fxs/README.md
  #       shell: bash

  # read-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Configure AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-region: eu-west-1
  #         role-to-assume: ${{ secrets.test-fxs }}
  #         role-session-name: OIDCSession

  #     - run: aws s3 cp s3://test-fxs/README.md README.md
  #       shell: bash

